# Generated by Django 5.0.6 on 2024-06-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='food_images')),
            ],
        ),
    ]
