# Generated by Django 5.0.6 on 2024-06-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcode', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.FileField(upload_to=''),
        ),
    ]
