# Generated by Django 5.0.6 on 2024-06-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcode', '0007_alter_cart_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
