# Generated by Django 5.0.6 on 2024-07-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcode', '0008_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True, unique_for_month=9)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('No_of_People', models.IntegerField()),
                ('message', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=40)),
                ('message', models.TextField(max_length=400)),
            ],
        ),
    ]
