# Generated by Django 5.0.6 on 2024-07-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcode', '0010_booktable_datebooked_message_datemessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='No_of_People',
            new_name='NoOfPeople',
        ),
    ]
