# Generated by Django 5.0.6 on 2024-07-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcode', '0011_rename_no_of_people_booktable_noofpeople'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='NoOfPeople',
            new_name='no_of_people',
        ),
        migrations.AlterField(
            model_name='booktable',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
